# Generated by Django 4.2.4 on 2023-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_products_discontinued_products_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=29900),
            preserve_default=False,
        ),
    ]
