# Generated by Django 4.2.4 on 2023-12-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='id_unico',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img4',
            field=models.ImageField(default=None, upload_to='img/'),
            preserve_default=False,
        ),
    ]
