# Generated by Django 4.2.4 on 2023-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_image_products_img1_remove_products_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id_unico',
        ),
        migrations.AlterField(
            model_name='products',
            name='ref',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
