# Generated by Django 4.2.4 on 2023-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_products_id_unico_alter_products_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
