# Generated by Django 4.2.4 on 2023-12-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_products_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
    ]
