# Generated by Django 4.2.4 on 2024-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_products_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_usd',
            field=models.IntegerField(default=11.45),
            preserve_default=False,
        ),
    ]
