# Generated by Django 4.2.4 on 2024-01-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_products_price_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_usd',
        ),
    ]
