# Generated by Django 4.2.4 on 2024-01-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_products_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_usd',
            field=models.FloatField(default=11.45),
            preserve_default=False,
        ),
    ]
