# Generated by Django 4.2.4 on 2024-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_products_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_dolar',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
