# Generated by Django 4.2.4 on 2024-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_products_price_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_dolar',
            field=models.FloatField(default=0),
        ),
    ]
