# Generated by Django 4.2.4 on 2024-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_products_price_dolar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_dolar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
